var gameData = [
{title:"Pokemon",
site:"Gog",
link:"https://www.gog.com/en/game/betrayer",
genre:"Action - Adventure - Horror","system":"Windows (7, 8, 10, 11)",
processor:"3.0 GHz dual core or better",
memory:"3 GB RAM",
graphics:"Graphics: DirectX 9 compatible with 1GB video RAM or better (NVIDIA GeForce GTX 460/AMD Radeon HD 6850)"},
{title:"Mega Man",
site:"Gog",
link:"https://www.gog.com/en/game/betrayer",
genre:"Action - Adventure - Horror","system":"Windows (7, 8, 10, 11)",
processor:"3.0 GHz dual core or better",
memory:"3 GB RAM",
graphics:"Graphics: DirectX 9 compatible with 1GB video RAM or better (NVIDIA GeForce GTX 460/AMD Radeon HD 6850)"},
{title:"Street Fighter",
site:"Gog",
link:"https://www.gog.com/en/game/megamanX",
genre:"Action - Adventure - Horror","system":"Windows (7, 8, 10, 11)",
processor:"3.0 GHz dual core or better",
memory:"3 GB RAM",
graphics:"Graphics: DirectX 9 compatible with 1GB video RAM or better (NVIDIA GeForce GTX 460/AMD Radeon HD 6850)"},
{title:"Mario Bros",
site:"Gog",
link:"https://www.gog.com/en/game/megamanX",
genre:"Action - Adventure - Horror","system":"Windows (7, 8, 10, 11)",
processor:"3.0 GHz dual core or better",
memory:"3 GB RAM",
graphics:"Graphics: DirectX 9 compatible with 1GB video RAM or better (NVIDIA GeForce GTX 460/AMD Radeon HD 6850)"}
]

module.exports = { gameData };